#
# before setup this CI, don't forget to add at ssh's host into /etc/ssh/sshd_config file this:
# ------
# AcceptEnv CI_*
# ------
# and restart sshd
#

image: docker:stable

stages:
  - test
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: unix:///var/run/docker.sock
  CI_DEV_API_PATH: /data/joinimpact/api
  
.job_template: &push_def
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

.job_template: &deploy_via_ssh_def
  script:
    - apk add --no-cache openssh-client
    - printf $SSH_KEY | base64 -d > /tmp/dev_ssh_key
    - chmod 400 /tmp/dev_ssh_key
    - printf "bash -x -c
      'cd $CI_DEV_API_PATH
      && docker-compose stop --timeout 90
      frontend
      && docker-compose pull --parallel -q
      frontend
      && docker-compose up --no-start
      frontend
      && docker-compose start
      frontend
      '"
      | ssh -T
      -o SendEnv="CI_*"
      -o StrictHostKeyChecking=no
      -o ConnectTimeout=30
      -o BatchMode=yes
      -i /tmp/dev_ssh_key
      $SSH_USER@$SSH_HOST
      -p $SSH_PORT

test:
  stage: test
  allow_failure: true
  image: node:12-alpine
  script:
    - npm version

build:
  stage: build
  allow_failure: false
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build . --pull -f Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

push:
  stage: push
  allow_failure: false
  <<: *push_def
  only:
    - master
    - /^r-.*$/

push-branch:
  stage: push
  <<: *push_def
  except:
    refs:
      - master
      - tags
  when: manual

push-tag:
  stage: push
  allow_failure: false
  <<: *push_def
  only:
    refs:
      - tags
    variables:
      - $PUSH_TAGS

deploy-dev:
  stage: deploy
  allow_failure: false
  <<: *deploy_via_ssh_def
  variables:
    SSH_KEY: $DEV_SSH_KEY
    SSH_USER: $DEV_SSH_USER
    SSH_HOST: $DEV_SSH_HOST
    SSH_PORT: $DEV_SSH_PORT
  environment:
    name: dev
    url: https://dev.joinimpact.org/
  only:
    - master
  except:
    variables:
      - $SKIP_DEPLOY
      - $SKIP_DEPLOY_DEV

deploy-dev-manual:
  stage: deploy
  <<: *deploy_via_ssh_def
  variables:
    SSH_KEY: $DEV_SSH_KEY
    SSH_USER: $DEV_SSH_USER
    SSH_HOST: $DEV_SSH_HOST
    SSH_PORT: $DEV_SSH_PORT
  dependencies:
    - push-branch
  environment:
    name: dev-manual
    url: https://dev.joinimpact.org/
  except:
    refs:
      - master
      - tags
    variables:
      - $SKIP_DEPLOY
      - $SKIP_DEPLOY_DEV
  when: manual
