import { IReduxState } from '../namespace';
import { initialCommunicationField } from 'shared/types/redux';

const initialState: IReduxState = {
  communications: {
    createOrganization: initialCommunicationField,
    updateOrganization: initialCommunicationField,
    uploadOrgLogo: initialCommunicationField,
    uploadEditableOrgLogo: initialCommunicationField,
    saveOrganizationTags: initialCommunicationField,
    saveEditableOrganizationTags: initialCommunicationField,
    saveOrganizationMembers: initialCommunicationField,
    saveEditableOrganizationMembers: initialCommunicationField,
    loadOrganizationTags: initialCommunicationField,
    requestNewOpportunityId: initialCommunicationField,
    updateOpportunity: initialCommunicationField,
    uploadOpportunityLogo: initialCommunicationField,
    loadOpportunities: initialCommunicationField,
    loadOpportunitiesWithEvents: initialCommunicationField,
    loadSingleOpportunity: initialCommunicationField,
    deleteOpportunity: initialCommunicationField,
    publicOpportunity: initialCommunicationField,
    unpublishOpportunity: initialCommunicationField,
    loadOpportunityVolunteers: initialCommunicationField,
    acceptInvitation: initialCommunicationField,
    declineInvitation: initialCommunicationField,
    editEvent: initialCommunicationField,
    deleteEvent: initialCommunicationField,
    loadEventResponses: initialCommunicationField,
    loadConversation: initialCommunicationField,
    loadConversations: initialCommunicationField,
    sendMessage: initialCommunicationField,
    setCurrentConversation: initialCommunicationField,
    fetchChatHistory: initialCommunicationField,
    chatStatePrepare: initialCommunicationField,
    acceptConversationInvite: initialCommunicationField,
    declineConversationInvite: initialCommunicationField,
    acceptHours: initialCommunicationField,
    declineHours: initialCommunicationField,
  },
  data: {
    uploadLogoProgress: null,
    currentOpportunity: null,
    uploadOpportunityLogoProgress: null,
    organizationOpportunities: [],
    deleteOpportunityId: null,
    currentOrganizationVolunteer: null,
    inviteVolunteersOpportunityId: null,
    opportunitiesWithEvents: [],
    currentEditEvent: null,
    currentEventResponses: [],
    editableOrganization: null,
    createNewOrganizationResponse: null,
    conversations: [],
    currentConversation: null,
    conversationItem: null,
    currentConversationMessages: [],
    totalMessagesCount: 0,
    currentConversationOpportunity: null,
  },
  modal: {
    showDeleteOpportunityConfirmation: false,
    createNewEvent: false,
  }
};

export default initialState;
